stages:
  stage_01:
    cmd: python stage_01.py
    deps:
      - stage_01.py
    outs:
      - Artifacts.txt
  stage_02:
    cmd: python stage_02.py
    deps:
      - stage_02.py
      - Artifacts.txt
  stage_03:
    cmd: python stage_03.py
    deps:
      - stage_03.py
      - Artifacts.txt
    outs:
      - Artifacts01.txt